// Each painting will have its image replaced with a real photo.
// To add a photo: add an `image` field with the path, e.g. image: '/paintings/morning-light.jpg'
// Then in PaintingImage.jsx, if image is present it will render as <img> instead of the SVG placeholder.

export const PAINTINGS = [
  {
    id: 1,
    title: 'Morning Light, Northumberland',
    medium: 'Oil on canvas',
    dimensions: '60 × 80 cm',
    price: 450,
    available: true,
    palette: ['#C4A870', '#8B6B3A', '#4A6B5A'],
  },
  {
    id: 2,
    title: 'Low Tide',
    medium: 'Watercolour',
    dimensions: '40 × 55 cm',
    price: 280,
    available: true,
    palette: ['#7AAAC4', '#3A6B8A', '#C4B88A'],
  },
  {
    id: 3,
    title: 'Autumn on the Fells',
    medium: 'Oil on canvas',
    dimensions: '50 × 70 cm',
    price: 380,
    available: false,
    palette: ['#C49060', '#8B5A28', '#6A4A20'],
  },
  {
    id: 4,
    title: 'The Harbour at Evening',
    medium: 'Oil on board',
    dimensions: '30 × 40 cm',
    price: 220,
    available: true,
    palette: ['#4A6070', '#2A3F50', '#C4A870'],
  },
  {
    id: 5,
    title: 'Wildflower Meadow',
    medium: 'Watercolour',
    dimensions: '35 × 50 cm',
    price: 240,
    available: true,
    palette: ['#8ABE72', '#C4D490', '#5A8A40'],
  },
  {
    id: 6,
    title: 'Storm Approaching',
    medium: 'Oil on canvas',
    dimensions: '70 × 90 cm',
    price: 580,
    available: false,
    palette: ['#606878', '#3A4258', '#C4B890'],
  },
  {
    id: 7,
    title: 'The Old Mill',
    medium: 'Watercolour',
    dimensions: '45 × 60 cm',
    price: 320,
    available: true,
    palette: ['#9A8060', '#C4A870', '#6A5A38'],
  },
  {
    id: 8,
    title: 'Coastal Path',
    medium: 'Oil on canvas',
    dimensions: '55 × 75 cm',
    price: 420,
    available: true,
    palette: ['#6A9A8A', '#4A7A6A', '#C4B890'],
  },
  {
    id: 9,
    title: 'Winter Trees',
    medium: 'Watercolour',
    dimensions: '30 × 45 cm',
    price: 195,
    available: false,
    palette: ['#9A9888', '#7A7868', '#C4C0B8'],
  },
  {
    id: 10,
    title: 'The Dales in Summer',
    medium: 'Oil on canvas',
    dimensions: '60 × 80 cm',
    price: 490,
    available: true,
    palette: ['#8AB060', '#C4C890', '#4A7A30'],
  },
  {
    id: 11,
    title: 'Harbour Wall',
    medium: 'Oil on board',
    dimensions: '25 × 35 cm',
    price: 175,
    available: true,
    palette: ['#B09070', '#8A6A48', '#4A7A8A'],
  },
  {
    id: 12,
    title: 'Misty Morning',
    medium: 'Watercolour',
    dimensions: '40 × 55 cm',
    price: 270,
    available: false,
    palette: ['#A8A8B8', '#888898', '#C8C8D4'],
  },
]
